const OFFICIAL_BASE = "https://clocktower-wiki.gstonegames.com/index.php?search=";

function sourceFor(term) {
  return OFFICIAL_BASE + encodeURIComponent(term);
}

function role(role) {
  return Object.assign({}, role, {
    sourceLink: sourceFor(role.name),
  });
}

const roles = [
  role({
    id: "washerwoman",
    name: "洗衣妇",
    nameEn: "Washerwoman",
    alignment: "good",
    alignmentLabel: "善良",
    roleType: "townsfolk",
    roleTypeLabel: "镇民",
    abilitySummary: "首夜得知两名玩家中有一位是特定镇民。",
    roleIconKey: "washerwoman",
    iconFallbackText: "洗",
    firstNightOrder: 1,
    otherNightOrder: null,
    wakeLabel: "首夜醒来，确认镇民线索",
  }),
  role({
    id: "librarian",
    name: "图书管理员",
    nameEn: "Librarian",
    alignment: "good",
    alignmentLabel: "善良",
    roleType: "townsfolk",
    roleTypeLabel: "镇民",
    abilitySummary: "首夜得知两名玩家中有一位是特定外来者，或得知没有此类信息。",
    roleIconKey: "librarian",
    iconFallbackText: "书",
    firstNightOrder: 2,
    otherNightOrder: null,
    wakeLabel: "首夜醒来，确认外来者线索",
  }),
  role({
    id: "investigator",
    name: "调查员",
    nameEn: "Investigator",
    alignment: "good",
    alignmentLabel: "善良",
    roleType: "townsfolk",
    roleTypeLabel: "镇民",
    abilitySummary: "首夜得知两名玩家中有一位是特定爪牙。",
    roleIconKey: "investigator",
    iconFallbackText: "调",
    firstNightOrder: 3,
    otherNightOrder: null,
    wakeLabel: "首夜醒来，确认爪牙线索",
  }),
  role({
    id: "chef",
    name: "厨师",
    nameEn: "Chef",
    alignment: "good",
    alignmentLabel: "善良",
    roleType: "townsfolk",
    roleTypeLabel: "镇民",
    abilitySummary: "首夜得知有多少对相邻的邪恶玩家。",
    roleIconKey: "chef",
    iconFallbackText: "厨",
    firstNightOrder: 4,
    otherNightOrder: null,
    wakeLabel: "首夜醒来，查看相邻邪恶对数",
  }),
  role({
    id: "empath",
    name: "共情者",
    nameEn: "Empath",
    alignment: "good",
    alignmentLabel: "善良",
    roleType: "townsfolk",
    roleTypeLabel: "镇民",
    abilitySummary: "每晚得知相邻两位玩家中有多少位是邪恶阵营。",
    roleIconKey: "empath",
    iconFallbackText: "情",
    firstNightOrder: 5,
    otherNightOrder: 1,
    wakeLabel: "每晚醒来，查看相邻邪恶数量",
  }),
  role({
    id: "fortune_teller",
    name: "占卜师",
    nameEn: "Fortune Teller",
    alignment: "good",
    alignmentLabel: "善良",
    roleType: "townsfolk",
    roleTypeLabel: "镇民",
    abilitySummary: "每晚选择两名玩家，若其中至少一位是恶魔则得知“是”，但本局会存在一个红鲱鱼。",
    roleIconKey: "fortune_teller",
    iconFallbackText: "卜",
    firstNightOrder: 6,
    otherNightOrder: 2,
    wakeLabel: "每晚醒来，查验两名玩家",
  }),
  role({
    id: "undertaker",
    name: "掘墓人",
    nameEn: "Undertaker",
    alignment: "good",
    alignmentLabel: "善良",
    roleType: "townsfolk",
    roleTypeLabel: "镇民",
    abilitySummary: "每晚得知当天被处决玩家的真实身份。",
    roleIconKey: "undertaker",
    iconFallbackText: "墓",
    firstNightOrder: null,
    otherNightOrder: 3,
    wakeLabel: "每晚醒来，查看被处决者身份",
  }),
  role({
    id: "monk",
    name: "僧侣",
    nameEn: "Monk",
    alignment: "good",
    alignmentLabel: "善良",
    roleType: "townsfolk",
    roleTypeLabel: "镇民",
    abilitySummary: "每晚选择一位玩家，使其今晚免受恶魔击杀。",
    roleIconKey: "monk",
    iconFallbackText: "僧",
    firstNightOrder: null,
    otherNightOrder: 4,
    wakeLabel: "每晚醒来，保护一位玩家",
  }),
  role({
    id: "ravenkeeper",
    name: "渡鸦饲养员",
    nameEn: "Ravenkeeper",
    alignment: "good",
    alignmentLabel: "善良",
    roleType: "townsfolk",
    roleTypeLabel: "镇民",
    abilitySummary: "若你在夜晚死亡，可立刻得知一名玩家的真实身份。",
    roleIconKey: "ravenkeeper",
    iconFallbackText: "鸦",
    firstNightOrder: null,
    otherNightOrder: null,
    wakeLabel: "夜死后触发一次身份查验",
  }),
  role({
    id: "virgin",
    name: "贞洁者",
    nameEn: "Virgin",
    alignment: "good",
    alignmentLabel: "善良",
    roleType: "townsfolk",
    roleTypeLabel: "镇民",
    abilitySummary: "若首次提名你的是镇民，则提名者立即死亡。",
    roleIconKey: "virgin",
    iconFallbackText: "贞",
    firstNightOrder: null,
    otherNightOrder: null,
    wakeLabel: "白天被首次提名时触发",
  }),
  role({
    id: "slayer",
    name: "杀手",
    nameEn: "Slayer",
    alignment: "good",
    alignmentLabel: "善良",
    roleType: "townsfolk",
    roleTypeLabel: "镇民",
    abilitySummary: "白天可公开指定一名玩家，若其为恶魔则立即死亡，只能使用一次。",
    roleIconKey: "slayer",
    iconFallbackText: "杀",
    firstNightOrder: null,
    otherNightOrder: null,
    wakeLabel: "白天一次性能力",
  }),
  role({
    id: "soldier",
    name: "士兵",
    nameEn: "Soldier",
    alignment: "good",
    alignmentLabel: "善良",
    roleType: "townsfolk",
    roleTypeLabel: "镇民",
    abilitySummary: "恶魔无法在夜晚将你击杀。",
    roleIconKey: "soldier",
    iconFallbackText: "兵",
    firstNightOrder: null,
    otherNightOrder: null,
    wakeLabel: "被动防护",
  }),
  role({
    id: "mayor",
    name: "市长",
    nameEn: "Mayor",
    alignment: "good",
    alignmentLabel: "善良",
    roleType: "townsfolk",
    roleTypeLabel: "镇民",
    abilitySummary: "若游戏结束时你存活且没有处决，善良阵营获胜；恶魔若夜袭你，可能改杀他人。",
    roleIconKey: "mayor",
    iconFallbackText: "长",
    firstNightOrder: null,
    otherNightOrder: null,
    wakeLabel: "终局与夜袭被动",
  }),
  role({
    id: "butler",
    name: "管家",
    nameEn: "Butler",
    alignment: "good",
    alignmentLabel: "善良",
    roleType: "outsider",
    roleTypeLabel: "外来者",
    abilitySummary: "你每晚选择一位主人；若主人未投票，你明天也不得投票。",
    roleIconKey: "butler",
    iconFallbackText: "管",
    firstNightOrder: 7,
    otherNightOrder: 5,
    wakeLabel: "每晚选择主人",
  }),
  role({
    id: "drunk",
    name: "醉鬼",
    nameEn: "Drunk",
    alignment: "good",
    alignmentLabel: "善良",
    roleType: "outsider",
    roleTypeLabel: "外来者",
    abilitySummary: "你认为自己是某个镇民，但能力实际上无效。",
    roleIconKey: "drunk",
    iconFallbackText: "醉",
    firstNightOrder: null,
    otherNightOrder: null,
    wakeLabel: "伪装为镇民",
  }),
  role({
    id: "recluse",
    name: "隐士",
    nameEn: "Recluse",
    alignment: "good",
    alignmentLabel: "善良",
    roleType: "outsider",
    roleTypeLabel: "外来者",
    abilitySummary: "你可能会被识别为邪恶或爪牙/恶魔。",
    roleIconKey: "recluse",
    iconFallbackText: "隐",
    firstNightOrder: null,
    otherNightOrder: null,
    wakeLabel: "被动误导",
  }),
  role({
    id: "saint",
    name: "圣徒",
    nameEn: "Saint",
    alignment: "good",
    alignmentLabel: "善良",
    roleType: "outsider",
    roleTypeLabel: "外来者",
    abilitySummary: "若你被处决，善良阵营立即失败。",
    roleIconKey: "saint",
    iconFallbackText: "圣",
    firstNightOrder: null,
    otherNightOrder: null,
    wakeLabel: "被处决时触发终局",
  }),
  role({
    id: "poisoner",
    name: "投毒者",
    nameEn: "Poisoner",
    alignment: "evil",
    alignmentLabel: "邪恶",
    roleType: "minion",
    roleTypeLabel: "爪牙",
    abilitySummary: "每晚选择一位玩家，使其能力在次日黄昏前失效。",
    roleIconKey: "poisoner",
    iconFallbackText: "毒",
    firstNightOrder: 8,
    otherNightOrder: 6,
    wakeLabel: "每晚选择中毒目标",
  }),
  role({
    id: "spy",
    name: "间谍",
    nameEn: "Spy",
    alignment: "evil",
    alignmentLabel: "邪恶",
    roleType: "minion",
    roleTypeLabel: "爪牙",
    abilitySummary: "每晚查看说书人的角色表，并可能被视作善良或镇民。",
    roleIconKey: "spy",
    iconFallbackText: "谍",
    firstNightOrder: 9,
    otherNightOrder: 7,
    wakeLabel: "每晚查看角色信息",
  }),
  role({
    id: "scarlet_woman",
    name: "猩红女巫",
    nameEn: "Scarlet Woman",
    alignment: "evil",
    alignmentLabel: "邪恶",
    roleType: "minion",
    roleTypeLabel: "爪牙",
    abilitySummary: "若恶魔死亡且仍有 5 名以上玩家存活，你会成为新的恶魔。",
    roleIconKey: "scarlet_woman",
    iconFallbackText: "绯",
    firstNightOrder: null,
    otherNightOrder: null,
    wakeLabel: "恶魔替补",
  }),
  role({
    id: "baron",
    name: "男爵",
    nameEn: "Baron",
    alignment: "evil",
    alignmentLabel: "邪恶",
    roleType: "minion",
    roleTypeLabel: "爪牙",
    abilitySummary: "本局额外加入 2 名外来者。",
    roleIconKey: "baron",
    iconFallbackText: "爵",
    firstNightOrder: null,
    otherNightOrder: null,
    wakeLabel: "发牌时生效",
  }),
  role({
    id: "imp",
    name: "小恶魔",
    nameEn: "Imp",
    alignment: "evil",
    alignmentLabel: "邪恶",
    roleType: "demon",
    roleTypeLabel: "恶魔",
    abilitySummary: "每晚击杀一名玩家；若自杀且猩红女巫满足条件，可能改由其继任。",
    roleIconKey: "imp",
    iconFallbackText: "魔",
    firstNightOrder: null,
    otherNightOrder: 8,
    wakeLabel: "每晚击杀一名玩家",
  }),
];

const troubleBrewing = {
  id: "trouble_brewing",
  name: "暗流涌动",
  nameEn: "Trouble Brewing",
  sourceLink: sourceFor("暗流涌动"),
  summary: "最经典的新手剧本，强调清晰的规则反馈、信息推理与白天提名投票，是 AI 说书人建模的最佳起点。",
  minPlayers: 5,
  maxPlayers: 15,
  iconMode: "text_fallback",
  roles,
  seatDistributions: {
    "5": { townsfolk: 3, outsiders: 0, minions: 1, demons: 1 },
    "6": { townsfolk: 3, outsiders: 1, minions: 1, demons: 1 },
    "7": { townsfolk: 5, outsiders: 0, minions: 1, demons: 1 },
    "8": { townsfolk: 5, outsiders: 1, minions: 1, demons: 1 },
    "9": { townsfolk: 5, outsiders: 2, minions: 1, demons: 1 },
    "10": { townsfolk: 7, outsiders: 0, minions: 2, demons: 1 },
    "11": { townsfolk: 7, outsiders: 1, minions: 2, demons: 1 },
    "12": { townsfolk: 7, outsiders: 2, minions: 2, demons: 1 },
    "13": { townsfolk: 9, outsiders: 0, minions: 3, demons: 1 },
    "14": { townsfolk: 9, outsiders: 1, minions: 3, demons: 1 },
    "15": { townsfolk: 9, outsiders: 2, minions: 3, demons: 1 }
  },
  terms: [
    {
      term: "醉酒 / 中毒",
      category: "状态",
      summary: "角色能力因醉酒或中毒而失效，但玩家通常不知道自己处于该状态。",
    },
    {
      term: "首夜 / 平夜",
      category: "流程",
      summary: "首夜信息型角色集中醒来，后续夜晚主要由持续型能力与恶魔行动推进。",
    },
    {
      term: "提名 / 投票",
      category: "白天流程",
      summary: "白天玩家可公开提名，达成过半票数则会处决目标。",
    },
  ],
  ruleIndex: [
    {
      title: "房间与人数配置",
      summary: "暗流涌动支持 5 到 15 名玩家，按人数配置镇民、外来者、爪牙和恶魔数量。",
      keywords: ["人数", "配角", "阵营"],
      sourceLink: sourceFor("暗流涌动"),
    },
    {
      title: "身份可见性",
      summary: "主持可见全量身份与私密状态，玩家默认只看到自己的身份与被授予的信息。",
      keywords: ["私密信息", "主持", "可见性"],
      sourceLink: sourceFor("规则"),
    },
    {
      title: "提名与投票",
      summary: "白天阶段可发起提名；多数通过时目标会被处决，并进入后续夜晚结算。",
      keywords: ["提名", "投票", "处决"],
      sourceLink: sourceFor("提名"),
    },
    {
      title: "醉酒与中毒",
      summary: "醉酒和中毒都会让能力失效，但不一定改变角色对自己身份的认知。",
      keywords: ["醉酒", "中毒", "能力失效"],
      sourceLink: sourceFor("中毒"),
    },
    {
      title: "夜晚行动顺序",
      summary: "夜间结算需遵循剧本夜序；首夜与平夜可唤醒的角色不同。",
      keywords: ["首夜", "平夜", "夜序"],
      sourceLink: sourceFor("夜晚"),
    },
    {
      title: "终局判定",
      summary: "小恶魔死亡通常触发善良获胜，但猩红女巫、市长、圣徒等会带来额外分支。",
      keywords: ["终局", "小恶魔", "圣徒", "市长"],
      sourceLink: sourceFor("胜利条件"),
    },
  ],
  faq: [
    {
      question: "为什么当前没有官方角色图标？",
      answer: "当前版本仅用于内部测试，未内置官方素材资源，只保留 role_icon_key 与资源切换位。",
    },
    {
      question: "为什么 AI 说书人不能直接改房间状态？",
      answer: "为了避免模型越权泄露身份或跳过规则，所有状态变更都必须先经过程序状态机与主持确认。",
    },
    {
      question: "为什么只做暗流涌动？",
      answer: "暗流涌动的规则反馈最清晰，适合作为 AI 主持与房间状态机的第一版验证脚本。",
    },
  ],
};

module.exports = {
  troubleBrewing,
  sourceFor,
};

